CREATE TABLE issuer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    corp_code VARCHAR(20) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    stock_code VARCHAR(20),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE bond (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issuer_id BIGINT NOT NULL,
    isin VARCHAR(32) NOT NULL UNIQUE,
    bond_code VARCHAR(40) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    issue_date DATE NOT NULL,
    maturity_date DATE NOT NULL,
    coupon_rate NUMERIC(7, 4) NOT NULL,
    credit_rating VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_bond_issuer FOREIGN KEY (issuer_id) REFERENCES issuer (id),
    CONSTRAINT ck_bond_dates CHECK (maturity_date > issue_date),
    CONSTRAINT ck_bond_coupon_rate CHECK (coupon_rate >= 0)
);

CREATE INDEX idx_bond_issuer_id ON bond (issuer_id);

CREATE TABLE holding (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bond_id BIGINT NOT NULL,
    purchase_date DATE NOT NULL,
    purchase_amount NUMERIC(19, 2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_holding_bond FOREIGN KEY (bond_id) REFERENCES bond (id),
    CONSTRAINT ck_holding_purchase_amount CHECK (purchase_amount > 0)
);

CREATE INDEX idx_holding_bond_id ON holding (bond_id);

CREATE TABLE watchlist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bond_id BIGINT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_watchlist_bond FOREIGN KEY (bond_id) REFERENCES bond (id)
);
