CREATE TABLE disclosure (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issuer_id BIGINT NOT NULL,
    receipt_no VARCHAR(14) NOT NULL UNIQUE,
    title VARCHAR(500) NOT NULL,
    disclosure_type VARCHAR(100) NOT NULL,
    published_at TIMESTAMP WITH TIME ZONE NOT NULL,
    latest_version_number INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_disclosure_issuer FOREIGN KEY (issuer_id) REFERENCES issuer (id),
    CONSTRAINT ck_disclosure_latest_version CHECK (latest_version_number >= 0)
);

CREATE INDEX idx_disclosure_issuer_published_at
    ON disclosure (issuer_id, published_at DESC);

CREATE TABLE disclosure_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    disclosure_id BIGINT NOT NULL,
    version_number INTEGER NOT NULL,
    source_receipt_no VARCHAR(14) NOT NULL,
    document_hash VARCHAR(64) NOT NULL,
    raw_content TEXT NOT NULL,
    normalized_content TEXT,
    published_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_disclosure_version_disclosure
        FOREIGN KEY (disclosure_id) REFERENCES disclosure (id),
    CONSTRAINT uq_disclosure_version_number
        UNIQUE (disclosure_id, version_number),
    CONSTRAINT uq_disclosure_version_hash
        UNIQUE (disclosure_id, document_hash),
    CONSTRAINT ck_disclosure_version_number CHECK (version_number > 0)
);

CREATE INDEX idx_disclosure_version_source_receipt
    ON disclosure_version (source_receipt_no);
