CREATE TABLE analysis_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    disclosure_version_id BIGINT NOT NULL,
    document_hash VARCHAR(64) NOT NULL,
    model VARCHAR(100) NOT NULL,
    prompt_version VARCHAR(50) NOT NULL,
    status VARCHAR(20) NOT NULL,
    input_tokens INTEGER,
    output_tokens INTEGER,
    latency_ms BIGINT,
    estimated_cost NUMERIC(18, 8),
    retry_count INTEGER NOT NULL DEFAULT 0,
    error_type VARCHAR(50),
    error_message VARCHAR(1000),
    started_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    success_key VARCHAR(64) UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_analysis_run_disclosure_version
        FOREIGN KEY (disclosure_version_id) REFERENCES disclosure_version (id),
    CONSTRAINT ck_analysis_run_status
        CHECK (status IN ('PENDING', 'PROCESSING', 'SUCCESS', 'FAILED')),
    CONSTRAINT ck_analysis_run_metrics
        CHECK (retry_count >= 0 AND (latency_ms IS NULL OR latency_ms >= 0))
);

CREATE INDEX idx_analysis_run_lookup
    ON analysis_run (document_hash, model, prompt_version, status);

CREATE TABLE candidate_risk_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_run_id BIGINT NOT NULL,
    issuer_id BIGINT NOT NULL,
    disclosure_version_id BIGINT NOT NULL,
    event_type VARCHAR(50) NOT NULL,
    event_date DATE,
    amount NUMERIC(30, 4),
    currency VARCHAR(10),
    purpose VARCHAR(100),
    evidence_text TEXT NOT NULL,
    extraction_reason TEXT,
    status VARCHAR(20) NOT NULL,
    fingerprint VARCHAR(64) NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_candidate_analysis_run
        FOREIGN KEY (analysis_run_id) REFERENCES analysis_run (id),
    CONSTRAINT fk_candidate_issuer
        FOREIGN KEY (issuer_id) REFERENCES issuer (id),
    CONSTRAINT fk_candidate_disclosure_version
        FOREIGN KEY (disclosure_version_id) REFERENCES disclosure_version (id),
    CONSTRAINT ck_candidate_event_type
        CHECK (event_type IN (
            'DEBT_INCREASE',
            'CASH_DECREASE',
            'OPERATING_LOSS',
            'CREDIT_RATING_CHANGE',
            'GUARANTEE_INCREASE',
            'LIQUIDITY_WARNING'
        )),
    CONSTRAINT ck_candidate_status CHECK (status = 'PENDING')
);

CREATE INDEX idx_candidate_analysis_run
    ON candidate_risk_event (analysis_run_id);
