ALTER TABLE candidate_risk_event
    DROP CONSTRAINT ck_candidate_status;

ALTER TABLE candidate_risk_event
    ADD COLUMN validation_reason TEXT;

ALTER TABLE candidate_risk_event
    ADD COLUMN validation_rule_version VARCHAR(50);

ALTER TABLE candidate_risk_event
    ADD COLUMN validated_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE candidate_risk_event
    ADD COLUMN canonical_risk_event_id BIGINT;

ALTER TABLE candidate_risk_event
    ADD CONSTRAINT ck_candidate_status
        CHECK (status IN ('PENDING', 'VERIFIED', 'REJECTED', 'SUPERSEDED'));

CREATE TABLE risk_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issuer_id BIGINT NOT NULL,
    disclosure_version_id BIGINT NOT NULL,
    candidate_risk_event_id BIGINT NOT NULL UNIQUE,
    event_type VARCHAR(50) NOT NULL,
    event_date DATE,
    category VARCHAR(50) NOT NULL,
    amount NUMERIC(30, 4),
    currency VARCHAR(10),
    purpose VARCHAR(100),
    event_fingerprint VARCHAR(64) NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_risk_event_issuer
        FOREIGN KEY (issuer_id) REFERENCES issuer (id),
    CONSTRAINT fk_risk_event_disclosure_version
        FOREIGN KEY (disclosure_version_id) REFERENCES disclosure_version (id),
    CONSTRAINT fk_risk_event_candidate
        FOREIGN KEY (candidate_risk_event_id) REFERENCES candidate_risk_event (id),
    CONSTRAINT ck_risk_event_type
        CHECK (event_type IN (
            'DEBT_INCREASE',
            'CASH_DECREASE',
            'OPERATING_LOSS',
            'CREDIT_RATING_CHANGE',
            'GUARANTEE_INCREASE',
            'LIQUIDITY_WARNING'
        )),
    CONSTRAINT ck_risk_event_category
        CHECK (category IN (
            'LEVERAGE',
            'LIQUIDITY',
            'PROFITABILITY',
            'CREDIT_QUALITY',
            'CONTINGENT_LIABILITY'
        ))
);

CREATE INDEX idx_risk_event_issuer_date
    ON risk_event (issuer_id, event_date);

CREATE TABLE risk_event_evidence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    risk_event_id BIGINT NOT NULL,
    disclosure_version_id BIGINT NOT NULL,
    section VARCHAR(500),
    evidence_text TEXT NOT NULL,
    source_url VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_risk_event_evidence_event
        FOREIGN KEY (risk_event_id) REFERENCES risk_event (id),
    CONSTRAINT fk_risk_event_evidence_version
        FOREIGN KEY (disclosure_version_id) REFERENCES disclosure_version (id)
);

CREATE INDEX idx_risk_event_evidence_event
    ON risk_event_evidence (risk_event_id);

ALTER TABLE candidate_risk_event
    ADD CONSTRAINT fk_candidate_canonical_risk_event
        FOREIGN KEY (canonical_risk_event_id) REFERENCES risk_event (id);
