CREATE TABLE financial_snapshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issuer_id BIGINT NOT NULL,
    reporting_period VARCHAR(20) NOT NULL,
    statement_date DATE NOT NULL,
    statement_scope VARCHAR(20) NOT NULL,
    cash NUMERIC(30, 4) NOT NULL,
    short_term_debt NUMERIC(30, 4) NOT NULL,
    long_term_debt NUMERIC(30, 4) NOT NULL,
    total_debt NUMERIC(30, 4) NOT NULL,
    operating_cash_flow NUMERIC(30, 4) NOT NULL,
    operating_profit NUMERIC(30, 4) NOT NULL,
    total_assets NUMERIC(30, 4),
    total_liabilities NUMERIC(30, 4),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_financial_snapshot_issuer
        FOREIGN KEY (issuer_id) REFERENCES issuer (id),
    CONSTRAINT uq_financial_snapshot_period_scope
        UNIQUE (issuer_id, reporting_period, statement_scope),
    CONSTRAINT ck_financial_snapshot_scope
        CHECK (statement_scope IN ('CONSOLIDATED')),
    CONSTRAINT ck_financial_snapshot_balances
        CHECK (
            cash >= 0 AND short_term_debt >= 0 AND long_term_debt >= 0 AND total_debt >= 0
            AND (total_assets IS NULL OR total_assets >= 0)
            AND (total_liabilities IS NULL OR total_liabilities >= 0)
        )
);

CREATE INDEX idx_financial_snapshot_issuer_date
    ON financial_snapshot (issuer_id, statement_date DESC);

CREATE TABLE issuer_risk_snapshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issuer_id BIGINT NOT NULL,
    snapshot_date DATE NOT NULL,
    liquidity_state VARCHAR(16) NOT NULL,
    cash_flow_state VARCHAR(16) NOT NULL,
    leverage_state VARCHAR(16) NOT NULL,
    earnings_state VARCHAR(16) NOT NULL,
    credit_state VARCHAR(16) NOT NULL,
    rule_version VARCHAR(50) NOT NULL,
    source_financial_snapshot_id BIGINT,
    input_fingerprint VARCHAR(64) NOT NULL,
    decision_trace TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_issuer_risk_snapshot_issuer
        FOREIGN KEY (issuer_id) REFERENCES issuer (id),
    CONSTRAINT fk_issuer_risk_snapshot_financial
        FOREIGN KEY (source_financial_snapshot_id) REFERENCES financial_snapshot (id),
    CONSTRAINT uq_issuer_risk_snapshot_date_rule
        UNIQUE (issuer_id, snapshot_date, rule_version),
    CONSTRAINT ck_issuer_risk_snapshot_states
        CHECK (
            liquidity_state IN ('NORMAL', 'WATCH', 'CAUTION')
            AND cash_flow_state IN ('NORMAL', 'WATCH', 'CAUTION')
            AND leverage_state IN ('NORMAL', 'WATCH', 'CAUTION')
            AND earnings_state IN ('NORMAL', 'WATCH', 'CAUTION')
            AND credit_state IN ('NORMAL', 'WATCH', 'CAUTION')
        )
);

CREATE INDEX idx_issuer_risk_snapshot_issuer_date
    ON issuer_risk_snapshot (issuer_id, snapshot_date DESC);

CREATE TABLE risk_change (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issuer_id BIGINT NOT NULL,
    category VARCHAR(30) NOT NULL,
    previous_state VARCHAR(16) NOT NULL,
    current_state VARCHAR(16) NOT NULL,
    previous_snapshot_id BIGINT,
    current_snapshot_id BIGINT NOT NULL,
    detected_at TIMESTAMP WITH TIME ZONE NOT NULL,
    rule_version VARCHAR(50) NOT NULL,
    CONSTRAINT fk_risk_change_issuer
        FOREIGN KEY (issuer_id) REFERENCES issuer (id),
    CONSTRAINT fk_risk_change_previous_snapshot
        FOREIGN KEY (previous_snapshot_id) REFERENCES issuer_risk_snapshot (id),
    CONSTRAINT fk_risk_change_current_snapshot
        FOREIGN KEY (current_snapshot_id) REFERENCES issuer_risk_snapshot (id),
    CONSTRAINT uq_risk_change_current_category
        UNIQUE (current_snapshot_id, category),
    CONSTRAINT ck_risk_change_category
        CHECK (category IN ('LIQUIDITY', 'CASH_FLOW', 'LEVERAGE', 'EARNINGS', 'CREDIT')),
    CONSTRAINT ck_risk_change_states
        CHECK (
            previous_state IN ('NORMAL', 'WATCH', 'CAUTION')
            AND current_state IN ('NORMAL', 'WATCH', 'CAUTION')
            AND previous_state <> current_state
        )
);
