CREATE TABLE since_bought_explanation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    holding_id BIGINT NOT NULL,
    input_fingerprint VARCHAR(64) NOT NULL UNIQUE,
    model VARCHAR(100) NOT NULL,
    prompt_version VARCHAR(50) NOT NULL,
    summary TEXT NOT NULL,
    related_event_ids TEXT NOT NULL,
    related_risk_change_ids TEXT NOT NULL,
    input_tokens INTEGER,
    output_tokens INTEGER,
    latency_ms BIGINT NOT NULL,
    estimated_cost NUMERIC(18, 8),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_since_bought_explanation_holding
        FOREIGN KEY (holding_id) REFERENCES holding (id) ON DELETE CASCADE,
    CONSTRAINT ck_since_bought_explanation_metrics
        CHECK (
            latency_ms >= 0
            AND (input_tokens IS NULL OR input_tokens >= 0)
            AND (output_tokens IS NULL OR output_tokens >= 0)
        )
);

CREATE INDEX idx_since_bought_explanation_holding
    ON since_bought_explanation (holding_id, created_at DESC);
