CREATE TABLE alert (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    holding_id BIGINT,
    watchlist_id BIGINT,
    bond_id BIGINT NOT NULL,
    issuer_id BIGINT NOT NULL,
    risk_event_id BIGINT,
    risk_change_id BIGINT,
    severity VARCHAR(16) NOT NULL,
    title VARCHAR(200) NOT NULL,
    message VARCHAR(800) NOT NULL,
    fingerprint VARCHAR(64) NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    read_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uq_alert_fingerprint UNIQUE (fingerprint),
    CONSTRAINT fk_alert_holding FOREIGN KEY (holding_id) REFERENCES holding(id) ON DELETE CASCADE,
    CONSTRAINT fk_alert_watchlist FOREIGN KEY (watchlist_id) REFERENCES watchlist(id) ON DELETE CASCADE,
    CONSTRAINT fk_alert_bond FOREIGN KEY (bond_id) REFERENCES bond(id),
    CONSTRAINT fk_alert_issuer FOREIGN KEY (issuer_id) REFERENCES issuer(id),
    CONSTRAINT ck_alert_target CHECK (
        (holding_id IS NOT NULL AND watchlist_id IS NULL)
        OR (holding_id IS NULL AND watchlist_id IS NOT NULL)
    ),
    CONSTRAINT ck_alert_source CHECK (risk_event_id IS NOT NULL OR risk_change_id IS NOT NULL),
    CONSTRAINT ck_alert_severity CHECK (severity IN ('INFO', 'WATCH', 'IMPORTANT')),
    CONSTRAINT ck_alert_read_state CHECK (
        (is_read = FALSE AND read_at IS NULL)
        OR (is_read = TRUE AND read_at IS NOT NULL)
    )
);

CREATE INDEX idx_alert_unread_created ON alert (is_read, created_at DESC);
CREATE INDEX idx_alert_holding_created ON alert (holding_id, created_at DESC);
CREATE INDEX idx_alert_watchlist_created ON alert (watchlist_id, created_at DESC);

